spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    initializationMode: always
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  mail:
    host: 0.0.0.0
    port: 3025
    username: hello@gmail.com
    password: 123
    properties.mail.smtp.auth: false
    properties.mail.smtp.starttls.enable: false

server:
  port: 8081

client:
  location:
    url: http://localhost:3000
logging:
  level:
    org.springframework: DEBUG

jwt:
  uri: /auth/**
  header: Authorization
  prefix: Bearer
  expiration: 300
  secret: JwtSuperBigFuckYeahWhatElseToWriteOMGSecretKey
