spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    initializationMode: always
  sql:
    init:
      mode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

server:
  port: 8081

client:
  location:
    url: http://localhost:3000
logging:
  level:
    org.springframework: DEBUG

jwt:
  uri: /auth/**
  header: Authorization
  prefix: Bearer
  expiration: 300
  secret: JwtSuperBigFuckYeahWhatElseToWriteOMGSecretKey

mail:
  host: localhost
  port: 3025
  username: hello@gmail.com
  password: 123
  from: noreply@gmail.com
  protocol: smtp
  auth: true
  tls: true
  debug: true