spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    initializationMode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8081

jwt:
  uri: /auth/**
  header: Authorization
  prefix: Bearer
  expiration: 300
  secret: JwtSecretKey
